const brand = {
  name: 'Green House',
  tagline: 'Cafe & Restaurant',
  tableLabel: 'TABLE 7 · DINE IN',
  heroMessage: 'Fresh Food, Great Taste',
}

const categories = [
  { id: 'burgers', name: 'Burgers', emoji: '🍔', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80' },
  { id: 'pizza', name: 'Pizza', emoji: '🍕', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80' },
  { id: 'chicken', name: 'Chicken', emoji: '🍗', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=800&q=80' },
  { id: 'pasta', name: 'Pasta', emoji: '🍝', image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=800&q=80' },
  { id: 'salads', name: 'Salads', emoji: '🥗', image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=800&q=80' },
  { id: 'desserts', name: 'Desserts', emoji: '🍰', image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80' },
  { id: 'coffee', name: 'Coffee', emoji: '☕', image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80' },
  { id: 'tea', name: 'Tea', emoji: '🍵', image: 'https://images.unsplash.com/photo-1509475662017-2ad8c2f7b0d0?auto=format&fit=crop&w=800&q=80' },
  { id: 'juices', name: 'Fresh Juices', emoji: '🧃', image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=800&q=80' },
  { id: 'soft-drinks', name: 'Soft Drinks', emoji: '🥤', image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=800&q=80' },
  { id: 'mocktails', name: 'Mocktails', emoji: '🍹', image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80' },
]

const item = (overrides) => ({
  prepTime: '12 min',
  tags: [],
  customizations: [],
  reviewCount: 120,
  ...overrides,
})

const items = [
  // Burgers
  item({
    id: 'double-smash-burger',
    categoryId: 'burgers',
    name: 'Double Smash Burger',
    description: 'Two smashed beef patties, American cheese, caramelized onions, special sauce on a toasted bun.',
    price: 400,
    rating: 4.9,
    reviewCount: 218,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
    popular: true,
    featured: true,
    prepTime: '15 min',
    tags: ['Beef', 'Best Seller'],
    customizations: [
      { label: 'Extra cheese', price: 50 },
      { label: 'Add fries', price: 70 },
      { label: 'Spicy sauce', price: 30 },
    ],
  }),
  item({
    id: 'classic-beef-burger',
    categoryId: 'burgers',
    name: 'Classic Beef Burger',
    description: 'Grilled beef patty, cheese, lettuce, tomato, and house pickles on a soft brioche bun.',
    price: 350,
    rating: 4.8,
    reviewCount: 186,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',
    popular: true,
    prepTime: '12 min',
    tags: ['Beef', 'Classic'],
    customizations: [
      { label: 'Extra patty', price: 120 },
      { label: 'Add bacon', price: 80 },
    ],
  }),
  item({
    id: 'veggie-burger',
    categoryId: 'burgers',
    name: 'Garden Veggie Burger',
    description: 'Crispy veggie patty, avocado, tomato, and herb mayo on a whole-grain bun.',
    price: 320,
    rating: 4.6,
    reviewCount: 94,
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=900&q=80',
    tags: ['Vegetarian', 'Healthy'],
    customizations: [{ label: 'Add cheese', price: 40 }],
  }),

  // Pizza
  item({
    id: 'margherita-pizza',
    categoryId: 'pizza',
    name: 'Margherita Pizza',
    description: 'Classic tomato sauce, fresh mozzarella, basil leaves, drizzled with extra virgin olive oil.',
    price: 500,
    rating: 4.7,
    reviewCount: 276,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80',
    popular: true,
    featured: true,
    prepTime: '18 min',
    tags: ['Italian', 'Vegetarian'],
    customizations: [
      { label: 'Extra mozzarella', price: 60 },
      { label: 'Add olives', price: 40 },
    ],
  }),
  item({
    id: 'pepperoni-pizza',
    categoryId: 'pizza',
    name: 'Pepperoni Pizza',
    description: 'Stone-baked crust topped with rich tomato sauce, mozzarella, and spicy pepperoni slices.',
    price: 550,
    rating: 4.8,
    reviewCount: 203,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=900&q=80',
    popular: true,
    tags: ['Spicy', 'Classic'],
    customizations: [{ label: 'Extra pepperoni', price: 70 }],
  }),
  item({
    id: 'bbq-chicken-pizza',
    categoryId: 'pizza',
    name: 'BBQ Chicken Pizza',
    description: 'Smoky BBQ sauce, grilled chicken, red onion, and melted cheese on crispy dough.',
    price: 580,
    rating: 4.7,
    reviewCount: 145,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80',
    tags: ['Chicken', 'BBQ'],
  }),

  // Chicken
  item({
    id: 'grilled-herb-chicken',
    categoryId: 'chicken',
    name: 'Grilled Herb Chicken',
    description: 'Free-range chicken marinated in fresh herbs, garlic, lemon, served with roasted vegetables.',
    price: 600,
    rating: 4.8,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=900&q=80',
    featured: true,
    prepTime: '20 min',
    tags: ['Protein', 'Healthy'],
    customizations: [
      { label: 'Add mashed potato', price: 80 },
      { label: 'Make it spicy', price: 20 },
    ],
  }),
  item({
    id: 'crispy-fried-chicken',
    categoryId: 'chicken',
    name: 'Crispy Fried Chicken',
    description: 'Golden fried chicken pieces with secret spice blend, served with honey mustard dip.',
    price: 450,
    rating: 4.7,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=80',
    popular: true,
    tags: ['Crispy', 'Comfort Food'],
    customizations: [{ label: 'Extra dip', price: 25 }],
  }),
  item({
    id: 'chicken-shawarma-plate',
    categoryId: 'chicken',
    name: 'Chicken Shawarma Plate',
    description: 'Tender marinated chicken strips with garlic sauce, pickles, and warm flatbread.',
    price: 420,
    rating: 4.6,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1529006557810-274b0b3c86c8?auto=format&fit=crop&w=900&q=80',
    tags: ['Middle Eastern', 'Popular'],
  }),

  // Pasta
  item({
    id: 'creamy-pesto-pasta',
    categoryId: 'pasta',
    name: 'Creamy Pesto Pasta',
    description: 'Basil pesto cream sauce with parmesan, cherry tomatoes, and toasted pine nuts.',
    price: 450,
    rating: 4.6,
    reviewCount: 132,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80',
    tags: ['Vegetarian', 'Creamy'],
    customizations: [{ label: 'Add grilled chicken', price: 120 }],
  }),
  item({
    id: 'alfredo-pasta',
    categoryId: 'pasta',
    name: 'Chicken Alfredo Pasta',
    description: 'Silky alfredo sauce tossed with fettuccine and grilled chicken strips.',
    price: 480,
    rating: 4.7,
    reviewCount: 111,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023324a?auto=format&fit=crop&w=900&q=80',
    popular: true,
    tags: ['Creamy', 'Chicken'],
  }),
  item({
    id: 'spaghetti-bolognese',
    categoryId: 'pasta',
    name: 'Spaghetti Bolognese',
    description: 'Slow-cooked beef ragu with fresh herbs served over al dente spaghetti.',
    price: 460,
    rating: 4.8,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1622973536968-3ead9e166900?auto=format&fit=crop&w=900&q=80',
    tags: ['Beef', 'Italian'],
  }),

  // Salads
  item({
    id: 'garden-salad-bowl',
    categoryId: 'salads',
    name: 'Garden Salad Bowl',
    description: 'Seasonal greens, avocado, cucumber, tomatoes, and house lemon dressing.',
    price: 350,
    rating: 4.5,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=900&q=80',
    prepTime: '10 min',
    tags: ['Vegan', 'Fresh'],
    customizations: [{ label: 'Add grilled chicken', price: 120 }],
  }),
  item({
    id: 'caesar-salad',
    categoryId: 'salads',
    name: 'Classic Caesar Salad',
    description: 'Crisp romaine, parmesan crisps, croutons, and creamy Caesar dressing.',
    price: 380,
    rating: 4.6,
    reviewCount: 102,
    image: 'https://images.unsplash.com/photo-1550304943-8f0367c9d73a?auto=format&fit=crop&w=900&q=80',
    tags: ['Classic', 'Light'],
  }),
  item({
    id: 'greek-salad',
    categoryId: 'salads',
    name: 'Greek Salad',
    description: 'Feta cheese, olives, cucumber, tomato, and oregano vinaigrette.',
    price: 360,
    rating: 4.5,
    reviewCount: 76,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80',
    tags: ['Mediterranean', 'Vegetarian'],
  }),

  // Desserts
  item({
    id: 'chocolate-lava-cake',
    categoryId: 'desserts',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center served with vanilla cream.',
    price: 300,
    rating: 4.9,
    reviewCount: 241,
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=900&q=80',
    popular: true,
    prepTime: '9 min',
    tags: ['Sweet', 'Warm'],
    customizations: [{ label: 'Extra ice cream', price: 50 }],
  }),
  item({
    id: 'new-york-cheesecake',
    categoryId: 'desserts',
    name: 'New York Cheesecake',
    description: 'Rich creamy cheesecake with berry compote and biscuit crust.',
    price: 280,
    rating: 4.8,
    reviewCount: 165,
    image: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=900&q=80',
    tags: ['Creamy', 'Popular'],
  }),
  item({
    id: 'tiramisu',
    categoryId: 'desserts',
    name: 'Classic Tiramisu',
    description: 'Espresso-soaked ladyfingers layered with mascarpone and cocoa dust.',
    price: 320,
    rating: 4.7,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1571877227209-a0d97ea90c0b?auto=format&fit=crop&w=900&q=80',
    tags: ['Italian', 'Coffee'],
  }),

  // Coffee
  item({
    id: 'signature-latte',
    categoryId: 'coffee',
    name: 'Signature Latte',
    description: 'Double espresso with silky milk foam and house-made vanilla.',
    price: 50,
    rating: 4.8,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
    popular: true,
    featured: true,
    prepTime: '6 min',
    tags: ['Coffee', 'Creamy'],
    customizations: [
      { label: 'Oat milk', price: 10 },
      { label: 'Extra shot', price: 15 },
    ],
  }),
  item({
    id: 'espresso',
    categoryId: 'coffee',
    name: 'Espresso',
    description: 'Bold single-origin espresso shot with a rich crema finish.',
    price: 40,
    rating: 4.7,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=900&q=80',
    prepTime: '4 min',
    tags: ['Strong', 'Classic'],
  }),
  item({
    id: 'cappuccino',
    categoryId: 'coffee',
    name: 'Cappuccino',
    description: 'Perfect balance of espresso, steamed milk, and velvety foam.',
    price: 55,
    rating: 4.8,
    reviewCount: 224,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=80',
    popular: true,
    prepTime: '5 min',
    tags: ['Coffee', 'Foam'],
  }),
  item({
    id: 'iced-matcha-latte',
    categoryId: 'coffee',
    name: 'Iced Matcha Latte',
    description: 'Ceremonial grade matcha over cold oat milk with a soft sweet finish.',
    price: 65,
    rating: 4.7,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80',
    popular: true,
    prepTime: '5 min',
    tags: ['Cold Drink', 'Matcha'],
  }),

  // Tea
  item({
    id: 'iced-tea',
    categoryId: 'tea',
    name: 'Iced Tea',
    description: 'Fresh brewed tea served over ice with a light citrus note.',
    price: 30,
    rating: 4.6,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80',
    popular: true,
    prepTime: '4 min',
    tags: ['Tea', 'Refreshing'],
  }),
  item({
    id: 'hot-tea',
    categoryId: 'tea',
    name: 'Hot Black Tea',
    description: 'Classic Ethiopian black tea served hot with honey on the side.',
    price: 25,
    rating: 4.5,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1509475662017-2ad8c2f7b0d0?auto=format&fit=crop&w=900&q=80',
    prepTime: '3 min',
    tags: ['Hot', 'Classic'],
  }),
  item({
    id: 'mint-tea',
    categoryId: 'tea',
    name: 'Fresh Mint Tea',
    description: 'Steeped garden mint leaves with a soothing herbal aroma.',
    price: 35,
    rating: 4.7,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80',
    tags: ['Herbal', 'Calming'],
  }),

  // Juices
  item({
    id: 'tropical-fresh-juice',
    categoryId: 'juices',
    name: 'Tropical Fresh Juice',
    description: 'Pineapple, mango, orange, and mint blended into a bright house refresher.',
    price: 150,
    rating: 4.6,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=900&q=80',
    prepTime: '4 min',
    tags: ['Fresh', 'Vitamin Boost'],
    customizations: [{ label: 'Add ginger', price: 20 }],
  }),
  item({
    id: 'orange-juice',
    categoryId: 'juices',
    name: 'Fresh Orange Juice',
    description: 'Cold-pressed oranges squeezed to order for maximum freshness.',
    price: 120,
    rating: 4.7,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=900&q=80',
    tags: ['Citrus', 'Fresh'],
  }),
  item({
    id: 'mango-juice',
    categoryId: 'juices',
    name: 'Mango Bliss Juice',
    description: 'Sweet ripe mango blended smooth with a touch of lime.',
    price: 140,
    rating: 4.8,
    reviewCount: 165,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80',
    popular: true,
    tags: ['Tropical', 'Sweet'],
  }),
  item({
    id: 'avocado-smoothie',
    categoryId: 'juices',
    name: 'Avocado Smoothie',
    description: 'Creamy avocado blended with milk and honey for a filling drink.',
    price: 160,
    rating: 4.6,
    reviewCount: 93,
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=900&q=80',
    tags: ['Creamy', 'Healthy'],
  }),

  // Soft drinks
  item({
    id: 'coca-cola',
    categoryId: 'soft-drinks',
    name: 'Coca-Cola',
    description: 'Chilled classic cola served with ice in a tall glass.',
    price: 40,
    rating: 4.5,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=900&q=80',
    prepTime: '1 min',
    tags: ['Cold', 'Classic'],
  }),
  item({
    id: 'sprite',
    categoryId: 'soft-drinks',
    name: 'Sprite',
    description: 'Crisp lemon-lime soda served ice cold.',
    price: 40,
    rating: 4.4,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?auto=format&fit=crop&w=900&q=80',
    prepTime: '1 min',
    tags: ['Cold', 'Lemon-Lime'],
  }),
  item({
    id: 'fanta',
    categoryId: 'soft-drinks',
    name: 'Fanta Orange',
    description: 'Bright orange soda with a bubbly refreshing finish.',
    price: 40,
    rating: 4.5,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?auto=format&fit=crop&w=900&q=80',
    prepTime: '1 min',
    tags: ['Cold', 'Orange'],
  }),

  // Mocktails
  item({
    id: 'virgin-mojito',
    categoryId: 'mocktails',
    name: 'Virgin Mojito',
    description: 'Fresh mint, lime, soda, and crushed ice for a zesty alcohol-free cooler.',
    price: 180,
    rating: 4.8,
    reviewCount: 127,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=80',
    popular: true,
    tags: ['Mint', 'Refreshing'],
  }),
  item({
    id: 'sunset-cooler',
    categoryId: 'mocktails',
    name: 'Sunset Cooler',
    description: 'Passion fruit, orange, and grenadine layered into a tropical sunset drink.',
    price: 200,
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=80',
    tags: ['Tropical', 'Fruity'],
  }),
  item({
    id: 'berry-fizz',
    categoryId: 'mocktails',
    name: 'Berry Fizz',
    description: 'Mixed berries, lemon, and sparkling soda with a sweet tangy twist.',
    price: 190,
    rating: 4.6,
    reviewCount: 84,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=80',
    tags: ['Berry', 'Sparkling'],
  }),
]

const promos = [
  {
    id: 'promo-1',
    kicker: 'Fresh Food, Great Taste',
    title: 'Welcome to Green House',
    subtitle: 'Scan, browse, and order from your table in seconds.',
    badge: 'QR Menu',
  },
  {
    id: 'promo-2',
    kicker: 'Daily Special',
    title: '20% Off Combo Meals',
    subtitle: 'Burger + fries + drink or pizza + soft drink pairings.',
    badge: 'Limited Time',
  },
  {
    id: 'promo-3',
    kicker: 'Cafe Hours',
    title: 'Fresh Coffee from 50 birr',
    subtitle: 'Latte, espresso, and cappuccino brewed to order.',
    badge: 'Hot & Iced',
  },
]

const combos = [
  {
    id: 'combo-1',
    title: 'Burger + Fries + Drink',
    subtitle: '400 birr burger with fries and a cold drink.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'combo-2',
    title: 'Pizza + Soft Drink',
    subtitle: 'Stone-baked pizza paired with your favorite soda.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'combo-3',
    title: 'Coffee + Dessert',
    subtitle: 'Perfect afternoon pairing from 50 birr coffee.',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
  },
]

module.exports = {
  brand,
  categories,
  items,
  promos,
  combos,
}
